import assert from "node:assert/strict";
import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { test } from "node:test";
import { representativeRootFor } from "../fixtures/roots.ts";
import {
  assertGolden,
  conjugate,
  describeArabic,
  listPatterns,
  MOODS,
  openDatabase,
  type PatternRow,
  PERSONS,
  verbalNouns,
} from "../harness";

const GOLDEN_DIR = join(import.meta.dirname, "..", "golden", "paradigms");
const LABEL_WIDTH = 56;

const db = await openDatabase();
const patterns = await listPatterns(db);

const slugify = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const goldenNameFor = (pattern: PatternRow): string => {
  const base = `form-${String(pattern.form_number).padStart(2, "0")}`;
  const slug = slugify(pattern.description);
  return slug ? `${base}-${slug}` : base;
};

const cellLine = (label: string, value: string | null): string =>
  `${label.padEnd(LABEL_WIDTH)}${describeArabic(value)}`;

const overrideRoots = new Map<number, string>();
for (const row of await db.rows<{ morph_pattern_id: number; root: string }>(
  "SELECT morph_pattern_id, root FROM lexical_pattern_override ORDER BY morph_pattern_id, root",
)) {
  if (!overrideRoots.has(row.morph_pattern_id)) {
    overrideRoots.set(row.morph_pattern_id, row.root);
  }
}

const rootOf = (pattern: PatternRow): string =>
  overrideRoots.get(pattern.id) ??
  representativeRootFor(pattern.radical1_kind, pattern.radical2_kind, pattern.radical3_kind, pattern.is_geminate);

const renderPattern = async (pattern: PatternRow): Promise<string> => {
  const root = rootOf(pattern);
  const nouns = await verbalNouns(db, root, pattern.id);
  const paradigm = await conjugate(db, root, pattern.id);
  const label = pattern.description === "" ? "(base pattern)" : `"${pattern.description}"`;
  const vowels =
    pattern.perfect_vowel && pattern.imperfect_vowel ? `${pattern.perfect_vowel} ~ ${pattern.imperfect_vowel}` : "none";

  const lines: string[] = [
    `# generated by tests/paradigm/goldens.test.ts - regenerate with UPDATE_GOLDENS=1`,
    `# form ${pattern.form_number} ${label}`,
    `# template        ${describeArabic(pattern.vocalic_template)}`,
    `# radicals        ${pattern.radical1_kind} / ${pattern.radical2_kind} / ${pattern.radical3_kind}`,
    `# geminate        ${pattern.is_geminate}`,
    `# form I vowels   ${vowels}`,
    `# no_affix        ${pattern.no_affix}`,
    `# root            ${describeArabic(root)}`,
    "",
    cellLine("masdar", nouns.masdar),
    cellLine("active_participle", nouns.active_participle),
    cellLine("passive_participle", nouns.passive_participle),
  ];

  const unexpected: string[] = [];
  for (const mood of MOODS) {
    const cells: Record<string, string | undefined> = paradigm[mood] ?? {};
    lines.push("");
    for (const person of PERSONS) {
      lines.push(cellLine(`${mood}/${person}`, cells[person] ?? null));
    }
    for (const key of Object.keys(cells).sort()) {
      if (!(PERSONS as readonly string[]).includes(key)) {
        unexpected.push(cellLine(`${mood}/${key}`, cells[key] ?? null));
      }
    }
  }

  if (unexpected.length > 0) {
    lines.push("", "# person keys outside the person_type enum", ...unexpected);
  }

  return `${lines.join("\n")}\n`;
};

test("each pattern maps to a distinct golden file name", () => {
  const names = patterns.map(goldenNameFor);
  assert.equal(new Set(names).size, names.length, `golden file names collide: ${names.join(", ")}`);
});

for (const pattern of patterns) {
  const label = pattern.description === "" ? "base pattern" : pattern.description;
  test(`form ${pattern.form_number} (${label}) paradigm matches its golden`, async () => {
    await assertGolden(`paradigms/${goldenNameFor(pattern)}.txt`, await renderPattern(pattern));
  });
}

test("every golden on disk belongs to a pattern in the database", async () => {
  const onDisk = (await readdir(GOLDEN_DIR)).filter((name) => name.endsWith(".txt")).sort();
  const expected = patterns.map((pattern) => `${goldenNameFor(pattern)}.txt`).sort();
  assert.deepEqual(onDisk, expected);
});
