export * from "./affixRules";
export * from "./conjugation";
export * from "./lexicalEntry";
export * from "./lexicalPatternOverride";
export * from "./morphPattern";
export * from "./sense";
export * from "./senseRelation";
export * from "./translationLink";
export * from "./views";
