INSERT INTO morph_pattern (form_number, vocalic_template, description, rules)
VALUES (1,
        'فَعَلَ',
        'a ~ u',
        '{
          "masdar": "{1}َ{2}ْ{3}",
          "perfect": "{1}َ{2}َ{3}",
          "imperative": "اُ{1}ْ{2}ُ{3}",
          "imperfect_stem": "{1}ْ{2}ُ{3}",
          "active_participle": "{1}َا{2}ِ{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (1,
        'فَعَلَ',
        'a ~ a',
        '{
          "masdar": "{1}َ{2}ْ{3}",
          "perfect": "{1}َ{2}َ{3}",
          "imperative": "اِ{1}ْ{2}َ{3}",
          "imperfect_stem": "{1}ْ{2}َ{3}",
          "active_participle": "{1}َا{2}ِ{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (1,
        'فَعَلَ',
        'a ~ i',
        '{
          "masdar": "{1}َ{2}ْ{3}",
          "perfect": "{1}َ{2}َ{3}",
          "imperative": "اِ{1}ْ{2}ِ{3}",
          "imperfect_stem": "{1}ْ{2}ِ{3}",
          "active_participle": "{1}َا{2}ِ{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (1,
        'فَعِلَ',
        'i ~ i',
        '{
          "masdar": "{1}َ{2}ْ{3}",
          "perfect": "{1}َ{2}ِ{3}",
          "imperative": "اِ{1}ْ{2}ِ{3}",
          "imperfect_stem": "{1}ْ{2}ِ{3}",
          "active_participle": "أَ{1}ْ{2}َ{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (1,
        'فَعِلَ',
        'i ~ a',
        '{
          "masdar": "{1}َ{2}ْ{3}",
          "perfect": "{1}َ{2}ِ{3}",
          "imperative": "اِ{1}ْ{2}َ{3}",
          "imperfect_stem": "{1}ْ{2}َ{3}",
          "active_participle": "{1}َا{2}ِ{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (1,
        'فَعُلَ',
        'u ~ u',
        '{
          "masdar": "{1}ُ{2}ْ{3}",
          "perfect": "{1}َ{2}ُ{3}",
          "imperative": "اُ{1}ْ{2}ُ{3}",
          "imperfect_stem": "{1}ْ{2}ُ{3}",
          "active_participle": "{1}َ{2}ِي{3}",
          "passive_participle": "مَ{1}ْ{2}ُو{3}"
        }'::jsonb),
       (2,
        'فَعَّلَ',
        '',
        '{
          "masdar": "تَ{1}ْ{2}ِي{3}",
          "perfect": "{1}َ{2}َّ{3}",
          "imperative": "{1}َ{2}ِّ{3}",
          "imperfect_stem": "{1}َ{2}ِّ{3}",
          "active_participle": "مُ{1}َ{2}ِّ{3}",
          "passive_participle": "مُ{1}َ{2}َّ{3}"
        }'::jsonb),
       (3,
        'فَاعَلَ',
        '',
        '{
          "masdar": "مُ{1}َا{2}َ{3}َة",
          "perfect": "{1}َا{2}َ{3}",
          "imperative": "{1}َا{2}ِ{3}",
          "imperfect_stem": "{1}َا{2}ِ{3}",
          "active_participle": "مُ{1}َا{2}ِ{3}",
          "passive_participle": "مُ{1}َا{2}َ{3}"
        }'::jsonb),
       (4,
        'أَفْعَلَ',
        '',
        '{
          "masdar": "إِ{1}ْ{2}َا{3}",
          "perfect": "أَ{1}ْ{2}َ{3}",
          "imperative": "أَ{1}ْ{2}ِ{3}",
          "imperfect_stem": "{1}ْ{2}ِ{3}",
          "active_participle": "مُ{1}ْ{2}ِ{3}",
          "passive_participle": "مُ{1}ْ{2}َ{3}"
        }'::jsonb),
       (5,
        'تَفَعَّلَ',
        '',
        '{
          "masdar": "تَ{1}َ{2}ُّ{3}",
          "perfect": "تَ{1}َ{2}َّ{3}",
          "imperative": "تَ{1}َ{2}َّ{3}",
          "imperfect_stem": "تَ{1}َ{2}َّ{3}",
          "active_participle": "مُتَ{1}َ{2}ِّ{3}",
          "passive_participle": "مُتَ{1}َ{2}َّ{3}"
        }'::jsonb),
       (6,
        'تَفَاعَلَ',
        '',
        '{
          "masdar": "تَ{1}َا{2}ُ{3}",
          "perfect": "تَ{1}َا{2}َ{3}",
          "imperative": "تَ{1}َا{2}َ{3}",
          "imperfect_stem": "تَ{1}َا{2}َ{3}",
          "active_participle": "مُتَ{1}َا{2}ِ{3}",
          "passive_participle": "مُتَ{1}َا{2}َ{3}"
        }'::jsonb),
       (7,
        'اِنْفَعَلَ',
        '',
        '{
          "masdar": "اِنْ{1}ِ{2}َا{3}",
          "perfect": "اِنْ{1}َ{2}َ{3}",
          "imperative": "اِنْ{1}َ{2}ِ{3}",
          "imperfect_stem": "نْ{1}َ{2}ِ{3}",
          "active_participle": "مُنْ{1}َ{2}ِ{3}",
          "passive_participle": "مُنْ{1}َ{2}َ{3}"
        }'::jsonb),
       (8,
        'اِفْتَعَلَ',
        '',
        '{
          "masdar": "اِ{1}ْتِ{2}َا{3}",
          "perfect": "اِ{1}ْتَ{2}َ{3}",
          "imperative": "اِ{1}ْتَ{2}ِ{3}",
          "imperfect_stem": "{1}ْتَ{2}ِ{3}",
          "active_participle": "مُ{1}ْتَ{2}ِ{3}",
          "passive_participle": "مُ{1}ْتَ{2}َ{3}"
        }'::jsonb),
       (10,
        'اِسْتَفْعَلَ',
        '',
        '{
          "masdar": "اِسْتِ{1}ْ{2}َا{3}",
          "perfect": "اِسْتَ{1}ْ{2}َ{3}",
          "imperative": "اِسْتَ{1}ْ{2}ِ{3}",
          "imperfect_stem": "سْتَ{1}ْ{2}ِ{3}",
          "active_participle": "مُسْتَ{1}ْ{2}ِ{3}",
          "passive_participle": "مُسْتَ{1}ْ{2}َ{3}"
        }'::jsonb);

INSERT INTO morph_pattern (form_number, vocalic_template, description, rules)
VALUES (1,
        'فَعَلَ',
        'a ~ u, hollow waw',
        '{
          "masdar": "{1}{2}{3}",
          "perfect": {
            "second_person_dual": "{1}ُ{3}ْتُمَا",
            "first_person_plural": "{1}ُ{3}ْنَا",
            "first_person_singular": "{1}ُ{3}ْتُ",
            "third_person_feminine_dual": "{1}َا{3}َتَا",
            "third_person_masculine_dual": "{1}َا{3}َا",
            "third_person_feminine_plural": "{1}ُ{3}ْنَ",
            "second_person_feminine_plural": "{1}ُ{3}ْتُنَّ",
            "third_person_masculine_plural": "{1}َا{3}ُوا",
            "second_person_masculine_plural": "{1}ُ{3}ْتُمْ",
            "third_person_feminine_singular": "{1}َا{3}َتْ",
            "second_person_feminine_singular": "{1}ُ{3}ْتِ",
            "third_person_masculine_singular": "{1}َا{3}َ",
            "second_person_masculine_singular": "{1}ُ{3}ْتَ"
          },
          "imperative": {
            "second_person_dual": "{1}ُ{2}{3}َا",
            "second_person_feminine_plural": "{1}ُ{3}ْنَ",
            "second_person_masculine_plural": "{1}ُ{2}{3}ُوا",
            "second_person_feminine_singular": "{1}ُ{2}{3}ِي",
            "second_person_masculine_singular": "{1}ُ{3}ْ"
          },
          "active_participle": "{1}َائِ{3}",
          "imperfect_jussive": {
            "second_person_dual": "{1}ُ{2}{3}",
            "first_person_plural": "{1}ُ{3}",
            "first_person_singular": "{1}ُ{3}",
            "third_person_feminine_dual": "{1}ُ{2}{3}",
            "third_person_masculine_dual": "{1}ُ{2}{3}",
            "third_person_feminine_plural": "{1}ُ{3}",
            "second_person_feminine_plural": "{1}ُ{3}",
            "third_person_masculine_plural": "{1}ُ{2}{3}",
            "second_person_masculine_plural": "{1}ُ{2}{3}",
            "third_person_feminine_singular": "{1}ُ{3}",
            "second_person_feminine_singular": "{1}ُ{2}{3}",
            "third_person_masculine_singular": "{1}ُ{3}",
            "second_person_masculine_singular": "{1}ُ{3}"
          },
          "passive_participle": "مَ{1}ُ{2}{3}",
          "imperfect_indicative": {
            "second_person_dual": "{1}ُ{2}{3}",
            "first_person_plural": "{1}ُ{2}{3}",
            "first_person_singular": "{1}ُ{2}{3}",
            "third_person_feminine_dual": "{1}ُ{2}{3}",
            "third_person_masculine_dual": "{1}ُ{2}{3}",
            "third_person_feminine_plural": "{1}ُ{3}",
            "second_person_feminine_plural": "{1}ُ{3}",
            "third_person_masculine_plural": "{1}ُ{2}{3}",
            "second_person_masculine_plural": "{1}ُ{2}{3}",
            "third_person_feminine_singular": "{1}ُ{2}{3}",
            "second_person_feminine_singular": "{1}ُ{2}{3}",
            "third_person_masculine_singular": "{1}ُ{2}{3}",
            "second_person_masculine_singular": "{1}ُ{2}{3}"
          },
          "imperfect_subjunctive": {
            "second_person_dual": "{1}ُ{2}{3}",
            "first_person_plural": "{1}ُ{2}{3}",
            "first_person_singular": "{1}ُ{2}{3}",
            "third_person_feminine_dual": "{1}ُ{2}{3}",
            "third_person_masculine_dual": "{1}ُ{2}{3}",
            "third_person_feminine_plural": "{1}ُ{3}",
            "second_person_feminine_plural": "{1}ُ{3}",
            "third_person_masculine_plural": "{1}ُ{2}{3}",
            "second_person_masculine_plural": "{1}ُ{2}{3}",
            "third_person_feminine_singular": "{1}ُ{2}{3}",
            "second_person_feminine_singular": "{1}ُ{2}{3}",
            "third_person_masculine_singular": "{1}ُ{2}{3}",
            "second_person_masculine_singular": "{1}ُ{2}{3}"
          }
        }'::jsonb),
       (1,
        'فَعَلَ',
        'a ~ i, hollow ya',
        '{
          "masdar": "{1}َيْ{3}",
          "perfect": {
            "second_person_dual": "{1}ِ{3}ْتُمَا",
            "first_person_plural": "{1}ِ{3}ْنَا",
            "first_person_singular": "{1}ِ{3}ْتُ",
            "third_person_feminine_dual": "{1}َا{3}َتَا",
            "third_person_masculine_dual": "{1}َا{3}َا",
            "third_person_feminine_plural": "{1}ِ{3}ْنَ",
            "second_person_feminine_plural": "{1}ِ{3}ْتُنَّ",
            "third_person_masculine_plural": "{1}َا{3}ُوا",
            "second_person_masculine_plural": "{1}ِ{3}ْتُمْ",
            "third_person_feminine_singular": "{1}َا{3}َتْ",
            "second_person_feminine_singular": "{1}ِ{3}ْتِ",
            "third_person_masculine_singular": "{1}َا{3}َ",
            "second_person_masculine_singular": "{1}ِ{3}ْتَ"
          },
          "imperative": {
            "second_person_dual": "{1}ِي{3}َا",
            "second_person_feminine_plural": "{1}ِ{3}ْنَ",
            "second_person_masculine_plural": "{1}ِي{3}ُوا",
            "second_person_feminine_singular": "{1}ِي{3}ِي",
            "second_person_masculine_singular": "{1}ِ{3}ْ"
          },
          "active_participle": "{1}َائِ{3}",
          "imperfect_jussive": {
            "second_person_dual": "{1}ِي{3}",
            "first_person_plural": "{1}ِ{3}",
            "first_person_singular": "{1}ِ{3}",
            "third_person_feminine_dual": "{1}ِي{3}",
            "third_person_masculine_dual": "{1}ِي{3}",
            "third_person_feminine_plural": "{1}ِ{3}",
            "second_person_feminine_plural": "{1}ِ{3}",
            "third_person_masculine_plural": "{1}ِي{3}",
            "second_person_masculine_plural": "{1}ِي{3}",
            "third_person_feminine_singular": "{1}ِ{3}",
            "second_person_feminine_singular": "{1}ِي{3}",
            "third_person_masculine_singular": "{1}ِ{3}",
            "second_person_masculine_singular": "{1}ِ{3}"
          },
          "passive_participle": "مَ{1}ِي{3}",
          "imperfect_indicative": {
            "second_person_dual": "{1}ِي{3}",
            "first_person_plural": "{1}ِي{3}",
            "first_person_singular": "{1}ِي{3}",
            "third_person_feminine_dual": "{1}ِي{3}",
            "third_person_masculine_dual": "{1}ِي{3}",
            "third_person_feminine_plural": "{1}ِ{3}",
            "second_person_feminine_plural": "{1}ِ{3}",
            "third_person_masculine_plural": "{1}ِي{3}",
            "second_person_masculine_plural": "{1}ِي{3}",
            "third_person_feminine_singular": "{1}ِي{3}",
            "second_person_feminine_singular": "{1}ِي{3}",
            "third_person_masculine_singular": "{1}ِي{3}",
            "second_person_masculine_singular": "{1}ِي{3}"
          },
          "imperfect_subjunctive": {
            "second_person_dual": "{1}ِي{3}",
            "first_person_plural": "{1}ِي{3}",
            "first_person_singular": "{1}ِي{3}",
            "third_person_feminine_dual": "{1}ِي{3}",
            "third_person_masculine_dual": "{1}ِي{3}",
            "third_person_feminine_plural": "{1}ِ{3}",
            "second_person_feminine_plural": "{1}ِ{3}",
            "third_person_masculine_plural": "{1}ِي{3}",
            "second_person_masculine_plural": "{1}ِي{3}",
            "third_person_feminine_singular": "{1}ِي{3}",
            "second_person_feminine_singular": "{1}ِي{3}",
            "third_person_masculine_singular": "{1}ِي{3}",
            "second_person_masculine_singular": "{1}ِي{3}"
          }
        }'::jsonb);

INSERT INTO morph_pattern (form_number, vocalic_template, description, rules, no_affix)
VALUES (1,
        'فَعَلَ',
        'a ~ a, final-weak',
        '{
          "masdar": "{1}َ{2}ْي",
          "active_participle": "{1}َا{2}ٍ",
          "passive_participle": "مَ{1}ْ{2}ِيّ",
          "perfect": {
            "first_person_singular": "{1}َ{2}َيْتُ",
            "second_person_masculine_singular": "{1}َ{2}َيْتَ",
            "second_person_feminine_singular": "{1}َ{2}َيْتِ",
            "third_person_masculine_singular": "{1}َ{2}َى",
            "third_person_feminine_singular": "{1}َ{2}َتْ",
            "second_person_dual": "{1}َ{2}َيْتُمَا",
            "third_person_masculine_dual": "{1}َ{2}َيَا",
            "third_person_feminine_dual": "{1}َ{2}َتَا",
            "first_person_plural": "{1}َ{2}َيْنَا",
            "second_person_masculine_plural": "{1}َ{2}َيْتُمْ",
            "second_person_feminine_plural": "{1}َ{2}َيْتُنَّ",
            "third_person_masculine_plural": "{1}َ{2}َوْا",
            "third_person_feminine_plural": "{1}َ{2}َيْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "اِ{1}ْ{2}َ",
            "second_person_feminine_singular": "اِ{1}ْ{2}َيْ",
            "second_person_dual": "اِ{1}ْ{2}َيَا",
            "second_person_masculine_plural": "اِ{1}ْ{2}َوْا",
            "second_person_feminine_plural": "اِ{1}ْ{2}َيْنَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَ{1}ْ{2}َى",
            "second_person_masculine_singular": "تَ{1}ْ{2}َى",
            "second_person_feminine_singular": "تَ{1}ْ{2}َيْنَ",
            "third_person_masculine_singular": "يَ{1}ْ{2}َى",
            "third_person_feminine_singular": "تَ{1}ْ{2}َى",
            "second_person_dual": "تَ{1}ْ{2}َيَانِ",
            "third_person_masculine_dual": "يَ{1}ْ{2}َيَانِ",
            "third_person_feminine_dual": "تَ{1}ْ{2}َيَانِ",
            "first_person_plural": "نَ{1}ْ{2}َى",
            "second_person_masculine_plural": "تَ{1}ْ{2}َوْنَ",
            "second_person_feminine_plural": "تَ{1}ْ{2}َيْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َوْنَ",
            "third_person_feminine_plural": "يَ{1}ْ{2}َيْنَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَ{1}ْ{2}َى",
            "second_person_masculine_singular": "تَ{1}ْ{2}َى",
            "second_person_feminine_singular": "تَ{1}ْ{2}َيْ",
            "third_person_masculine_singular": "يَ{1}ْ{2}َى",
            "third_person_feminine_singular": "تَ{1}ْ{2}َى",
            "second_person_dual": "تَ{1}ْ{2}َيَا",
            "third_person_masculine_dual": "يَ{1}ْ{2}َيَا",
            "third_person_feminine_dual": "تَ{1}ْ{2}َيَا",
            "first_person_plural": "نَ{1}ْ{2}َى",
            "second_person_masculine_plural": "تَ{1}ْ{2}َوْا",
            "second_person_feminine_plural": "تَ{1}ْ{2}َيْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َوْا",
            "third_person_feminine_plural": "يَ{1}ْ{2}َيْنَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَ{1}ْ{2}َ",
            "second_person_masculine_singular": "تَ{1}ْ{2}َ",
            "second_person_feminine_singular": "تَ{1}ْ{2}َيْ",
            "third_person_masculine_singular": "يَ{1}ْ{2}َ",
            "third_person_feminine_singular": "تَ{1}ْ{2}َ",
            "second_person_dual": "تَ{1}ْ{2}َيَا",
            "third_person_masculine_dual": "يَ{1}ْ{2}َيَا",
            "third_person_feminine_dual": "تَ{1}ْ{2}َيَا",
            "first_person_plural": "نَ{1}ْ{2}َ",
            "second_person_masculine_plural": "تَ{1}ْ{2}َوْا",
            "second_person_feminine_plural": "تَ{1}ْ{2}َيْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َوْا",
            "third_person_feminine_plural": "يَ{1}ْ{2}َيْنَ"
          }
        }'::jsonb,
        TRUE),
       (1,
        'فَعَلَ',
        'a ~ a, final-weak, hamzated middle',
        '{
          "masdar": "{1}ُؤْ{3}َة",
          "active_participle": "{1}َاءٍ",
          "passive_participle": "مَ{1}ْئِيّ",
          "perfect": {
            "first_person_singular": "{1}َ{2}َيْتُ",
            "second_person_masculine_singular": "{1}َ{2}َيْتَ",
            "second_person_feminine_singular": "{1}َ{2}َيْتِ",
            "third_person_masculine_singular": "{1}َ{2}َى",
            "third_person_feminine_singular": "{1}َ{2}َتْ",
            "second_person_dual": "{1}َ{2}َيْتُمَا",
            "third_person_masculine_dual": "{1}َ{2}َيَا",
            "third_person_feminine_dual": "{1}َ{2}َتَا",
            "first_person_plural": "{1}َ{2}َيْنَا",
            "second_person_masculine_plural": "{1}َ{2}َيْتُمْ",
            "second_person_feminine_plural": "{1}َ{2}َيْتُنَّ",
            "third_person_masculine_plural": "{1}َ{2}َوْا",
            "third_person_feminine_plural": "{1}َ{2}َيْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "{1}َ",
            "second_person_feminine_singular": "{1}َيْ",
            "second_person_dual": "{1}َيَا",
            "second_person_masculine_plural": "{1}َوْا",
            "second_person_feminine_plural": "{1}َيْنَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَ{1}َى",
            "second_person_masculine_singular": "تَ{1}َى",
            "second_person_feminine_singular": "تَ{1}َيْنَ",
            "third_person_masculine_singular": "يَ{1}َى",
            "third_person_feminine_singular": "تَ{1}َى",
            "second_person_dual": "تَ{1}َيَانِ",
            "third_person_masculine_dual": "يَ{1}َيَانِ",
            "third_person_feminine_dual": "تَ{1}َيَانِ",
            "first_person_plural": "نَ{1}َى",
            "second_person_masculine_plural": "تَ{1}َوْنَ",
            "second_person_feminine_plural": "تَ{1}َيْنَ",
            "third_person_masculine_plural": "يَ{1}َوْنَ",
            "third_person_feminine_plural": "يَ{1}َيْنَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَ{1}َى",
            "second_person_masculine_singular": "تَ{1}َى",
            "second_person_feminine_singular": "تَ{1}َيْ",
            "third_person_masculine_singular": "يَ{1}َى",
            "third_person_feminine_singular": "تَ{1}َى",
            "second_person_dual": "تَ{1}َيَا",
            "third_person_masculine_dual": "يَ{1}َيَا",
            "third_person_feminine_dual": "تَ{1}َيَا",
            "first_person_plural": "نَ{1}َى",
            "second_person_masculine_plural": "تَ{1}َوْا",
            "second_person_feminine_plural": "تَ{1}َيْنَ",
            "third_person_masculine_plural": "يَ{1}َوْا",
            "third_person_feminine_plural": "يَ{1}َيْنَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَ{1}َ",
            "second_person_masculine_singular": "تَ{1}َ",
            "second_person_feminine_singular": "تَ{1}َيْ",
            "third_person_masculine_singular": "يَ{1}َ",
            "third_person_feminine_singular": "تَ{1}َ",
            "second_person_dual": "تَ{1}َيَا",
            "third_person_masculine_dual": "يَ{1}َيَا",
            "third_person_feminine_dual": "تَ{1}َيَا",
            "first_person_plural": "نَ{1}َ",
            "second_person_masculine_plural": "تَ{1}َوْا",
            "second_person_feminine_plural": "تَ{1}َيْنَ",
            "third_person_masculine_plural": "يَ{1}َوْا",
            "third_person_feminine_plural": "يَ{1}َيْنَ"
          }
        }'::jsonb,
        TRUE),
       (1,
        'فَعَلَ',
        'a ~ i, geminate',
        '{
          "masdar": "{1}ُ{2}ّ",
          "active_participle": "{1}َا{2}ّ",
          "passive_participle": "مَ{1}ْ{2}ُو{3}",
          "perfect": {
            "first_person_singular": "{1}َ{2}َ{3}ْتُ",
            "second_person_masculine_singular": "{1}َ{2}َ{3}ْتَ",
            "second_person_feminine_singular": "{1}َ{2}َ{3}ْتِ",
            "third_person_masculine_singular": "{1}َ{2}َّ",
            "third_person_feminine_singular": "{1}َ{2}َّتْ",
            "second_person_dual": "{1}َ{2}َ{3}ْتُمَا",
            "third_person_masculine_dual": "{1}َ{2}َّا",
            "third_person_feminine_dual": "{1}َ{2}َّتَا",
            "first_person_plural": "{1}َ{2}َ{3}ْنَا",
            "second_person_masculine_plural": "{1}َ{2}َ{3}ْتُمْ",
            "second_person_feminine_plural": "{1}َ{2}َ{3}ْتُنَّ",
            "third_person_masculine_plural": "{1}َ{2}ُّوا",
            "third_person_feminine_plural": "{1}َ{2}َ{3}ْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "اِ{1}ْ{2}ِ{3}ْ",
            "second_person_feminine_singular": "{1}ِ{2}ِّي",
            "second_person_dual": "{1}ِ{2}َّا",
            "second_person_masculine_plural": "{1}ِ{2}ُّوا",
            "second_person_feminine_plural": "اِ{1}ْ{2}ِ{3}ْنَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَ{1}ِ{2}ُّ",
            "second_person_masculine_singular": "تَ{1}ِ{2}ُّ",
            "second_person_feminine_singular": "تَ{1}ِ{2}ِّينَ",
            "third_person_masculine_singular": "يَ{1}ِ{2}ُّ",
            "third_person_feminine_singular": "تَ{1}ِ{2}ُّ",
            "second_person_dual": "تَ{1}ِ{2}َّانِ",
            "third_person_masculine_dual": "يَ{1}ِ{2}َّانِ",
            "third_person_feminine_dual": "تَ{1}ِ{2}َّانِ",
            "first_person_plural": "نَ{1}ِ{2}ُّ",
            "second_person_masculine_plural": "تَ{1}ِ{2}ُّونَ",
            "second_person_feminine_plural": "تَ{1}ْ{2}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ِ{2}ُّونَ",
            "third_person_feminine_plural": "يَ{1}ْ{2}ِ{3}ْنَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَ{1}ِ{2}َّ",
            "second_person_masculine_singular": "تَ{1}ِ{2}َّ",
            "second_person_feminine_singular": "تَ{1}ِ{2}ِّي",
            "third_person_masculine_singular": "يَ{1}ِ{2}َّ",
            "third_person_feminine_singular": "تَ{1}ِ{2}َّ",
            "second_person_dual": "تَ{1}ِ{2}َّا",
            "third_person_masculine_dual": "يَ{1}ِ{2}َّا",
            "third_person_feminine_dual": "تَ{1}ِ{2}َّا",
            "first_person_plural": "نَ{1}ِ{2}َّ",
            "second_person_masculine_plural": "تَ{1}ِ{2}ُّوا",
            "second_person_feminine_plural": "تَ{1}ْ{2}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ِ{2}ُّوا",
            "third_person_feminine_plural": "يَ{1}ْ{2}ِ{3}ْنَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَ{1}ِ{2}َّ",
            "second_person_masculine_singular": "تَ{1}ِ{2}َّ",
            "second_person_feminine_singular": "تَ{1}ِ{2}ِّي",
            "third_person_masculine_singular": "يَ{1}ِ{2}َّ",
            "third_person_feminine_singular": "تَ{1}ِ{2}َّ",
            "second_person_dual": "تَ{1}ِ{2}َّا",
            "third_person_masculine_dual": "يَ{1}ِ{2}َّا",
            "third_person_feminine_dual": "تَ{1}ِ{2}َّا",
            "first_person_plural": "نَ{1}ِ{2}َّ",
            "second_person_masculine_plural": "تَ{1}ِ{2}ُّوا",
            "second_person_feminine_plural": "تَ{1}ْ{2}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ِ{2}ُّوا",
            "third_person_feminine_plural": "يَ{1}ْ{2}ِ{3}ْنَ"
          }
        }'::jsonb,
        TRUE),
       (4,
        'أَفْعَلَ',
        'final-weak',
        '{
          "masdar": "إِ{1}ْ{2}َاء",
          "active_participle": "مُ{1}ْ{2}ٍ",
          "passive_participle": "مُ{1}ْ{2}ًى",
          "perfect": {
            "first_person_singular": "أَ{1}ْ{2}َيْتُ",
            "second_person_masculine_singular": "أَ{1}ْ{2}َيْتَ",
            "second_person_feminine_singular": "أَ{1}ْ{2}َيْتِ",
            "third_person_masculine_singular": "أَ{1}ْ{2}َى",
            "third_person_feminine_singular": "أَ{1}ْ{2}َتْ",
            "second_person_dual": "أَ{1}ْ{2}َيْتُمَا",
            "third_person_masculine_dual": "أَ{1}ْ{2}َيَا",
            "third_person_feminine_dual": "أَ{1}ْ{2}َتَا",
            "first_person_plural": "أَ{1}ْ{2}َيْنَا",
            "second_person_masculine_plural": "أَ{1}ْ{2}َيْتُمْ",
            "second_person_feminine_plural": "أَ{1}ْ{2}َيْتُنَّ",
            "third_person_masculine_plural": "أَ{1}ْ{2}َوْا",
            "third_person_feminine_plural": "أَ{1}ْ{2}َيْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "أَ{1}ْ{2}ِ",
            "second_person_feminine_singular": "أَ{1}ْ{2}ِي",
            "second_person_dual": "أَ{1}ْ{2}ِيَا",
            "second_person_masculine_plural": "أَ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "أَ{1}ْ{2}ِينَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أُ{1}ْ{2}ِي",
            "second_person_masculine_singular": "تُ{1}ْ{2}ِي",
            "second_person_feminine_singular": "تُ{1}ْ{2}ِينَ",
            "third_person_masculine_singular": "يُ{1}ْ{2}ِي",
            "third_person_feminine_singular": "تُ{1}ْ{2}ِي",
            "second_person_dual": "تُ{1}ْ{2}ِيَانِ",
            "third_person_masculine_dual": "يُ{1}ْ{2}ِيَانِ",
            "third_person_feminine_dual": "تُ{1}ْ{2}ِيَانِ",
            "first_person_plural": "نُ{1}ْ{2}ِي",
            "second_person_masculine_plural": "تُ{1}ْ{2}ُونَ",
            "second_person_feminine_plural": "تُ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يُ{1}ْ{2}ُونَ",
            "third_person_feminine_plural": "يُ{1}ْ{2}ِينَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أُ{1}ْ{2}ِيَ",
            "second_person_masculine_singular": "تُ{1}ْ{2}ِيَ",
            "second_person_feminine_singular": "تُ{1}ْ{2}ِي",
            "third_person_masculine_singular": "يُ{1}ْ{2}ِيَ",
            "third_person_feminine_singular": "تُ{1}ْ{2}ِيَ",
            "second_person_dual": "تُ{1}ْ{2}ِيَا",
            "third_person_masculine_dual": "يُ{1}ْ{2}ِيَا",
            "third_person_feminine_dual": "تُ{1}ْ{2}ِيَا",
            "first_person_plural": "نُ{1}ْ{2}ِيَ",
            "second_person_masculine_plural": "تُ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "تُ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يُ{1}ْ{2}ُوا",
            "third_person_feminine_plural": "يُ{1}ْ{2}ِينَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أُ{1}ْ{2}ِ",
            "second_person_masculine_singular": "تُ{1}ْ{2}ِ",
            "second_person_feminine_singular": "تُ{1}ْ{2}ِي",
            "third_person_masculine_singular": "يُ{1}ْ{2}ِ",
            "third_person_feminine_singular": "تُ{1}ْ{2}ِ",
            "second_person_dual": "تُ{1}ْ{2}ِيَا",
            "third_person_masculine_dual": "يُ{1}ْ{2}ِيَا",
            "third_person_feminine_dual": "تُ{1}ْ{2}ِيَا",
            "first_person_plural": "نُ{1}ْ{2}ِ",
            "second_person_masculine_plural": "تُ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "تُ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يُ{1}ْ{2}ُوا",
            "third_person_feminine_plural": "يُ{1}ْ{2}ِينَ"
          }
        }'::jsonb,
        TRUE),
       (8, 'اِفْتَعَلَ', 'final‑weak ya', '{
         "masdar": "اِ{1}ْتِ{2}َاء",
         "active_participle": "مُ{1}ْتَ{2}ٍ",
         "passive_participle": "مُ{1}ْتَ{2}ًى",
         "perfect": {
           "first_person_singular": "اِ{1}ْتَ{2}َيْتُ",
           "second_person_masculine_singular": "اِ{1}ْتَ{2}َيْتَ",
           "second_person_feminine_singular": "اِ{1}ْتَ{2}َيْتِ",
           "third_person_masculine_singular": "اِ{1}ْتَ{2}َى",
           "third_person_feminine_singular": "اِ{1}ْتَ{2}َتْ",
           "second_person_dual": "اِ{1}ْتَ{2}َيْتُمَا",
           "third_person_masculine_dual": "اِ{1}ْتَ{2}َيَا",
           "third_person_feminine_dual": "اِ{1}ْتَ{2}َتَا",
           "first_person_plural": "اِ{1}ْتَ{2}َيْنَا",
           "second_person_masculine_plural": "اِ{1}ْتَ{2}َيْتُمْ",
           "second_person_feminine_plural": "اِ{1}ْتَ{2}َيْتُنَّ",
           "third_person_masculine_plural": "اِ{1}ْتَ{2}َوْا",
           "third_person_feminine_plural": "اِ{1}ْتَ{2}َيْنَ"
         },
         "imperative": {
           "second_person_masculine_singular": "اِ{1}ْتَ{2}ِ",
           "second_person_feminine_singular": "اِ{1}ْتَ{2}ِي",
           "second_person_dual": "اِ{1}ْتَ{2}ِيَا",
           "second_person_masculine_plural": "اِ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "اِ{1}ْتَ{2}ِينَ"
         },
         "imperfect_indicative": {
           "first_person_singular": "أَ{1}ْتَ{2}ِي",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِي",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِي",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَانِ",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَانِ",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَانِ",
           "first_person_plural": "نَ{1}ْتَ{2}ِي",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُونَ",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُونَ",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         },
         "imperfect_subjunctive": {
           "first_person_singular": "أَ{1}ْتَ{2}ِيَ",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِيَ",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِيَ",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِيَ",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَا",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَا",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَا",
           "first_person_plural": "نَ{1}ْتَ{2}ِيَ",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُوا",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         },
         "imperfect_jussive": {
           "first_person_singular": "أَ{1}ْتَ{2}ِ",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِ",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِ",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِ",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَا",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَا",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَا",
           "first_person_plural": "نَ{1}ْتَ{2}ِ",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُوا",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         }
       }'::jsonb, TRUE),
       (8, 'اِفْتَعَلَ', 'final‑weak waw', '{
         "masdar": "اِ{1}ْتِ{2}َاء",
         "active_participle": "مُ{1}ْتَ{2}ٍ",
         "passive_participle": "مُ{1}ْتَ{2}ًى",
         "perfect": {
           "first_person_singular": "اِ{1}ْتَ{2}َيْتُ",
           "second_person_masculine_singular": "اِ{1}ْتَ{2}َيْتَ",
           "second_person_feminine_singular": "اِ{1}ْتَ{2}َيْتِ",
           "third_person_masculine_singular": "اِ{1}ْتَ{2}َى",
           "third_person_feminine_singular": "اِ{1}ْتَ{2}َتْ",
           "second_person_dual": "اِ{1}ْتَ{2}َيْتُمَا",
           "third_person_masculine_dual": "اِ{1}ْتَ{2}َيَا",
           "third_person_feminine_dual": "اِ{1}ْتَ{2}َتَا",
           "first_person_plural": "اِ{1}ْتَ{2}َيْنَا",
           "second_person_masculine_plural": "اِ{1}ْتَ{2}َيْتُمْ",
           "second_person_feminine_plural": "اِ{1}ْتَ{2}َيْتُنَّ",
           "third_person_masculine_plural": "اِ{1}ْتَ{2}َوْا",
           "third_person_feminine_plural": "اِ{1}ْتَ{2}َيْنَ"
         },
         "imperative": {
           "second_person_masculine_singular": "اِ{1}ْتَ{2}ِ",
           "second_person_feminine_singular": "اِ{1}ْتَ{2}ِي",
           "second_person_dual": "اِ{1}ْتَ{2}ِيَا",
           "second_person_masculine_plural": "اِ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "اِ{1}ْتَ{2}ِينَ"
         },
         "imperfect_indicative": {
           "first_person_singular": "أَ{1}ْتَ{2}ِي",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِي",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِي",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَانِ",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَانِ",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَانِ",
           "first_person_plural": "نَ{1}ْتَ{2}ِي",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُونَ",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُونَ",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         },
         "imperfect_subjunctive": {
           "first_person_singular": "أَ{1}ْتَ{2}ِيَ",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِيَ",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِيَ",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِيَ",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَا",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَا",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَا",
           "first_person_plural": "نَ{1}ْتَ{2}ِيَ",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُوا",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         },
         "imperfect_jussive": {
           "first_person_singular": "أَ{1}ْتَ{2}ِ",
           "second_person_masculine_singular": "تَ{1}ْتَ{2}ِ",
           "second_person_feminine_singular": "تَ{1}ْتَ{2}ِي",
           "third_person_masculine_singular": "يَ{1}ْتَ{2}ِ",
           "third_person_feminine_singular": "تَ{1}ْتَ{2}ِ",
           "second_person_dual": "تَ{1}ْتَ{2}ِيَا",
           "third_person_masculine_dual": "يَ{1}ْتَ{2}ِيَا",
           "third_person_feminine_dual": "تَ{1}ْتَ{2}ِيَا",
           "first_person_plural": "نَ{1}ْتَ{2}ِ",
           "second_person_masculine_plural": "تَ{1}ْتَ{2}ُوا",
           "second_person_feminine_plural": "تَ{1}ْتَ{2}ِينَ",
           "third_person_masculine_plural": "يَ{1}ْتَ{2}ُوا",
           "third_person_feminine_plural": "يَ{1}ْتَ{2}ِينَ"
         }
       }'::jsonb, TRUE),
       (9,
        'اِفْعَلَّ',
        '',
        '{
          "masdar": "اِ{1}ْ{2}ِ{3}َا{3}",
          "active_participle": "مُ{1}ْ{2}َ{3}ّ",
          "perfect": {
            "first_person_singular": "اِ{1}ْ{2}َ{3}َ{3}ْتُ",
            "second_person_masculine_singular": "اِ{1}ْ{2}َ{3}َ{3}ْتَ",
            "second_person_feminine_singular": "اِ{1}ْ{2}َ{3}َ{3}ْتِ",
            "third_person_masculine_singular": "اِ{1}ْ{2}َ{3}َّ",
            "third_person_feminine_singular": "اِ{1}ْ{2}َ{3}َّتْ",
            "second_person_dual": "اِ{1}ْ{2}َ{3}َ{3}ْتُمَا",
            "third_person_masculine_dual": "اِ{1}ْ{2}َ{3}َّا",
            "third_person_feminine_dual": "اِ{1}ْ{2}َ{3}َّتَا",
            "first_person_plural": "اِ{1}ْ{2}َ{3}َ{3}ْنَا",
            "second_person_masculine_plural": "اِ{1}ْ{2}َ{3}َ{3}ْتُمْ",
            "second_person_feminine_plural": "اِ{1}ْ{2}َ{3}َ{3}ْتُنَّ",
            "third_person_masculine_plural": "اِ{1}ْ{2}َ{3}ُّوا",
            "third_person_feminine_plural": "اِ{1}ْ{2}َ{3}َ{3}ْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "اِ{1}ْ{2}َ{3}َّ",
            "second_person_feminine_singular": "اِ{1}ْ{2}َ{3}ِّي",
            "second_person_dual": "اِ{1}ْ{2}َ{3}َّا",
            "second_person_masculine_plural": "اِ{1}ْ{2}َ{3}ُّوا",
            "second_person_feminine_plural": "اِ{1}ْ{2}َ{3}ِ{3}ْنَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَ{1}ْ{2}َ{3}ُّ",
            "second_person_masculine_singular": "تَ{1}ْ{2}َ{3}ُّ",
            "second_person_feminine_singular": "تَ{1}ْ{2}َ{3}ِّينَ",
            "third_person_masculine_singular": "يَ{1}ْ{2}َ{3}ُّ",
            "third_person_feminine_singular": "تَ{1}ْ{2}َ{3}ُّ",
            "second_person_dual": "تَ{1}ْ{2}َ{3}َّانِ",
            "third_person_masculine_dual": "يَ{1}ْ{2}َ{3}َّانِ",
            "third_person_feminine_dual": "تَ{1}ْ{2}َ{3}َّانِ",
            "first_person_plural": "نَ{1}ْ{2}َ{3}ُّ",
            "second_person_masculine_plural": "تَ{1}ْ{2}َ{3}ُّونَ",
            "second_person_feminine_plural": "تَ{1}ْ{2}َ{3}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َ{3}ُّونَ",
            "third_person_feminine_plural": "يَ{1}ْ{2}َ{3}ِ{3}ْنَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَ{1}ْ{2}َ{3}َّ",
            "second_person_masculine_singular": "تَ{1}ْ{2}َ{3}َّ",
            "second_person_feminine_singular": "تَ{1}ْ{2}َ{3}ِّي",
            "third_person_masculine_singular": "يَ{1}ْ{2}َ{3}َّ",
            "third_person_feminine_singular": "تَ{1}ْ{2}َ{3}َّ",
            "second_person_dual": "تَ{1}ْ{2}َ{3}َّا",
            "third_person_masculine_dual": "يَ{1}ْ{2}َ{3}َّا",
            "third_person_feminine_dual": "تَ{1}ْ{2}َ{3}َّا",
            "first_person_plural": "نَ{1}ْ{2}َ{3}َّ",
            "second_person_masculine_plural": "تَ{1}ْ{2}َ{3}ُّوا",
            "second_person_feminine_plural": "تَ{1}ْ{2}َ{3}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َ{3}ُّوا",
            "third_person_feminine_plural": "يَ{1}ْ{2}َ{3}ِ{3}ْنَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَ{1}ْ{2}َ{3}َّ",
            "second_person_masculine_singular": "تَ{1}ْ{2}َ{3}َّ",
            "second_person_feminine_singular": "تَ{1}ْ{2}َ{3}ِّي",
            "third_person_masculine_singular": "يَ{1}ْ{2}َ{3}َّ",
            "third_person_feminine_singular": "تَ{1}ْ{2}َ{3}َّ",
            "second_person_dual": "تَ{1}ْ{2}َ{3}َّا",
            "third_person_masculine_dual": "يَ{1}ْ{2}َ{3}َّا",
            "third_person_feminine_dual": "تَ{1}ْ{2}َ{3}َّا",
            "first_person_plural": "نَ{1}ْ{2}َ{3}َّ",
            "second_person_masculine_plural": "تَ{1}ْ{2}َ{3}ُّوا",
            "second_person_feminine_plural": "تَ{1}ْ{2}َ{3}ِ{3}ْنَ",
            "third_person_masculine_plural": "يَ{1}ْ{2}َ{3}ُّوا",
            "third_person_feminine_plural": "يَ{1}ْ{2}َ{3}ِ{3}ْنَ"
          }
        }'::jsonb,
        TRUE),
       (10,
        'اِسْتَفْعَلَ',
        'final-weak',
        '{
          "masdar": "اِسْتِ{1}ْ{2}َاء",
          "active_participle": "مُسْتَ{1}ْ{2}ٍ",
          "passive_participle": "مُسْتَ{1}ْ{2}ًى",
          "perfect": {
            "first_person_singular": "اِسْتَ{1}ْ{2}َيْتُ",
            "second_person_masculine_singular": "اِسْتَ{1}ْ{2}َيْتَ",
            "second_person_feminine_singular": "اِسْتَ{1}ْ{2}َيْتِ",
            "third_person_masculine_singular": "اِسْتَ{1}ْ{2}َى",
            "third_person_feminine_singular": "اِسْتَ{1}ْ{2}َتْ",
            "second_person_dual": "اِسْتَ{1}ْ{2}َيْتُمَا",
            "third_person_masculine_dual": "اِسْتَ{1}ْ{2}َيَا",
            "third_person_feminine_dual": "اِسْتَ{1}ْ{2}َتَا",
            "first_person_plural": "اِسْتَ{1}ْ{2}َيْنَا",
            "second_person_masculine_plural": "اِسْتَ{1}ْ{2}َيْتُمْ",
            "second_person_feminine_plural": "اِسْتَ{1}ْ{2}َيْتُنَّ",
            "third_person_masculine_plural": "اِسْتَ{1}ْ{2}َوْا",
            "third_person_feminine_plural": "اِسْتَ{1}ْ{2}َيْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "اِسْتَ{1}ْ{2}ِ",
            "second_person_feminine_singular": "اِسْتَ{1}ْ{2}ِي",
            "second_person_dual": "اِسْتَ{1}ْ{2}ِيَا",
            "second_person_masculine_plural": "اِسْتَ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "اِسْتَ{1}ْ{2}ِينَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَسْتَ{1}ْ{2}ِي",
            "second_person_masculine_singular": "تَسْتَ{1}ْ{2}ِي",
            "second_person_feminine_singular": "تَسْتَ{1}ْ{2}ِينَ",
            "third_person_masculine_singular": "يَسْتَ{1}ْ{2}ِي",
            "third_person_feminine_singular": "تَسْتَ{1}ْ{2}ِي",
            "second_person_dual": "تَسْتَ{1}ْ{2}ِيَانِ",
            "third_person_masculine_dual": "يَسْتَ{1}ْ{2}ِيَانِ",
            "third_person_feminine_dual": "تَسْتَ{1}ْ{2}ِيَانِ",
            "first_person_plural": "نَسْتَ{1}ْ{2}ِي",
            "second_person_masculine_plural": "تَسْتَ{1}ْ{2}ُونَ",
            "second_person_feminine_plural": "تَسْتَ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يَسْتَ{1}ْ{2}ُونَ",
            "third_person_feminine_plural": "يَسْتَ{1}ْ{2}ِينَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَسْتَ{1}ْ{2}ِيَ",
            "second_person_masculine_singular": "تَسْتَ{1}ْ{2}ِيَ",
            "second_person_feminine_singular": "تَسْتَ{1}ْ{2}ِي",
            "third_person_masculine_singular": "يَسْتَ{1}ْ{2}ِيَ",
            "third_person_feminine_singular": "تَسْتَ{1}ْ{2}ِيَ",
            "second_person_dual": "تَسْتَ{1}ْ{2}ِيَا",
            "third_person_masculine_dual": "يَسْتَ{1}ْ{2}ِيَا",
            "third_person_feminine_dual": "تَسْتَ{1}ْ{2}ِيَا",
            "first_person_plural": "نَسْتَ{1}ْ{2}ِيَ",
            "second_person_masculine_plural": "تَسْتَ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "تَسْتَ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يَسْتَ{1}ْ{2}ُوا",
            "third_person_feminine_plural": "يَسْتَ{1}ْ{2}ِينَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَسْتَ{1}ْ{2}ِ",
            "second_person_masculine_singular": "تَسْتَ{1}ْ{2}ِ",
            "second_person_feminine_singular": "تَسْتَ{1}ْ{2}ِي",
            "third_person_masculine_singular": "يَسْتَ{1}ْ{2}ِ",
            "third_person_feminine_singular": "تَسْتَ{1}ْ{2}ِ",
            "second_person_dual": "تَسْتَ{1}ْ{2}ِيَا",
            "third_person_masculine_dual": "يَسْتَ{1}ْ{2}ِيَا",
            "third_person_feminine_dual": "تَسْتَ{1}ْ{2}ِيَا",
            "first_person_plural": "نَسْتَ{1}ْ{2}ِ",
            "second_person_masculine_plural": "تَسْتَ{1}ْ{2}ُوا",
            "second_person_feminine_plural": "تَسْتَ{1}ْ{2}ِينَ",
            "third_person_masculine_plural": "يَسْتَ{1}ْ{2}ُوا",
            "third_person_feminine_plural": "يَسْتَ{1}ْ{2}ِينَ"
          }
        }'::jsonb,
        TRUE),
       (10,
        'اِسْتَفْعَلَ',
        'hollow',
        '{
          "masdar": "اِسْتِ{1}َاعَة",
          "active_participle": "مُسْتَ{1}ِيع",
          "passive_participle": "مُسْتَ{1}َاع",
          "perfect": {
            "first_person_singular": "اِسْتَ{1}َعْتُ",
            "second_person_masculine_singular": "اِسْتَ{1}َعْتَ",
            "second_person_feminine_singular": "اِسْتَ{1}َعْتِ",
            "third_person_masculine_singular": "اِسْتَ{1}َاعَ",
            "third_person_feminine_singular": "اِسْتَ{1}َاعَتْ",
            "second_person_dual": "اِسْتَ{1}َعْتُمَا",
            "third_person_masculine_dual": "اِسْتَ{1}َاعَا",
            "third_person_feminine_dual": "اِسْتَ{1}َاعَتَا",
            "first_person_plural": "اِسْتَ{1}َعْنَا",
            "second_person_masculine_plural": "اِسْتَ{1}َعْتُمْ",
            "second_person_feminine_plural": "اِسْتَ{1}َعْتُنَّ",
            "third_person_masculine_plural": "اِسْتَ{1}َاعُوا",
            "third_person_feminine_plural": "اِسْتَ{1}َعْنَ"
          },
          "imperative": {
            "second_person_masculine_singular": "اِسْتَ{1}ِعْ",
            "second_person_feminine_singular": "اِسْتَ{1}ِيعِي",
            "second_person_dual": "اِسْتَ{1}ِيعَا",
            "second_person_masculine_plural": "اِسْتَ{1}ِيعُوا",
            "second_person_feminine_plural": "اِسْتَ{1}ِعْنَ"
          },
          "imperfect_indicative": {
            "first_person_singular": "أَسْتَ{1}ِيعُ",
            "second_person_masculine_singular": "تَسْتَ{1}ِيعُ",
            "second_person_feminine_singular": "تَسْتَ{1}ِيعِينَ",
            "third_person_masculine_singular": "يَسْتَ{1}ِيعُ",
            "third_person_feminine_singular": "تَسْتَ{1}ِيعُ",
            "second_person_dual": "تَسْتَ{1}ِيعَانِ",
            "third_person_masculine_dual": "يَسْتَ{1}ِيعَانِ",
            "third_person_feminine_dual": "تَسْتَ{1}ِيعَانِ",
            "first_person_plural": "نَسْتَ{1}ِيعُ",
            "second_person_masculine_plural": "تَسْتَ{1}ِيعُونَ",
            "second_person_feminine_plural": "تَسْتَ{1}ِعْنَ",
            "third_person_masculine_plural": "يَسْتَ{1}ِيعُونَ",
            "third_person_feminine_plural": "يَسْتَ{1}ِعْنَ"
          },
          "imperfect_subjunctive": {
            "first_person_singular": "أَسْتَ{1}ِيعَ",
            "second_person_masculine_singular": "تَسْتَ{1}ِيعَ",
            "second_person_feminine_singular": "تَسْتَ{1}ِيعِي",
            "third_person_masculine_singular": "يَسْتَ{1}ِيعَ",
            "third_person_feminine_singular": "تَسْتَ{1}ِيعَ",
            "second_person_dual": "تَسْتَ{1}ِيعَا",
            "third_person_masculine_dual": "يَسْتَ{1}ِيعَا",
            "third_person_feminine_dual": "تَسْتَ{1}ِيعَا",
            "first_person_plural": "نَسْتَ{1}ِيعَ",
            "second_person_masculine_plural": "تَسْتَ{1}ِيعُوا",
            "second_person_feminine_plural": "تَسْتَ{1}ِعْنَ",
            "third_person_masculine_plural": "يَسْتَ{1}ِيعُوا",
            "third_person_feminine_plural": "يَسْتَ{1}ِعْنَ"
          },
          "imperfect_jussive": {
            "first_person_singular": "أَسْتَ{1}ِعْ",
            "second_person_masculine_singular": "تَسْتَ{1}ِعْ",
            "second_person_feminine_singular": "تَسْتَ{1}ِيعِي",
            "third_person_masculine_singular": "يَسْتَ{1}ِعْ",
            "third_person_feminine_singular": "تَسْتَ{1}ِعْ",
            "second_person_dual": "تَسْتَ{1}ِيعَا",
            "third_person_masculine_dual": "يَسْتَ{1}ِيعَا",
            "third_person_feminine_dual": "تَسْتَ{1}ِيعَا",
            "first_person_plural": "نَسْتَ{1}ِعْ",
            "second_person_masculine_plural": "تَسْتَ{1}ِيعُوا",
            "second_person_feminine_plural": "تَسْتَ{1}ِعْنَ",
            "third_person_masculine_plural": "يَسْتَ{1}ِيعُوا",
            "third_person_feminine_plural": "يَسْتَ{1}ِعْنَ"
          }
        }'::jsonb,
        TRUE);
